---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: VMware 環境に関連するハードウェア要件と計画の問題がいくつかあります。 
---
= VMware ハイパーバイザーとハードウェアに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware 環境に関連するハードウェア要件と計画の問題がいくつかあります。



== ハイパーバイザーの要件

ONTAP Select を実行するハイパーバイザーに関連する要件がいくつかあります。


NOTE: 既知の制限事項や制限事項の追加に際しては、使用している ONTAP Select のバージョンの最新リリースノートを確認してください。



=== VMware ライセンス

ONTAP Select クラスタを導入するには、 ONTAP Select を実行するハイパーバイザーホストの有効な VMware vSphere ライセンスが必要です。導入に適したライセンスを使用してください。



=== ソフトウェアの互換性

ONTAP Select は次のハイパーバイザーに導入できます。

* Red Hat Enterprise Linux 8.6、8.7、8.8、9.0、9.1上のKVM および9.2
* Rocky Linux 8および9上のKVM
* VMware ESXi 7.0 GA（ビルド15849807以降）：7.0 U1、U2、U3Cを含む
* VMware ESXi 8.0 GA（ビルド20513097）
* VMware ESXi 8.0 U1（ビルド21495797）



NOTE: VMware でも同じバージョンがサポートされていれば、特定されたバージョンの ESXi で ONTAP Select がサポートされます。


NOTE: ESXi 6.5 GAおよびESXi 6.7 GAが販売終了に近づいています。これらのバージョンのONTAP Selectクラスタを使用している場合は、 https://mysupport.netapp.com/matrix["Interoperability Matrix Tool （ IMT ）"^]。



=== VMware ESXi 6.5 U2以降にアップグレードする

現在 ONTAP Select が VMware ESXi 6.5 U1 に導入されている場合は、できるだけ早く ESXi 6.5 U2 以降にアップグレードしてください。ESXi 6.5 U1 を使用すると、 VMware の既知のバグによって仮想マシンの障害にさらされる可能性があります。



=== VMware vCenter およびスタンドアロンの ESXi ホスト

ESXi ハイパーバイザーホストが vCenter サーバで管理されている場合は、 vCenter のクレデンシャルを使用して、ホストを Deploy 管理ユーティリティに登録する必要があります。ESXi のクレデンシャルを使用してホストをスタンドアロンホストとして登録することはできません。



== コアハードウェアの要件

ONTAP Select を導入する物理ハイパーバイザーホストが、いくつかのハードウェア要件を満たしている必要があります。ハードウェアの最小要件を満たしていれば、ハイパーバイザーホストに対して任意のプラットフォームを選択できます。サポートされているハードウェアプラットフォームは、 Cisco 、 Dell 、 HP 、富士通、 Lenovo 、 と Supermicro です。


NOTE: ONTAP Select 9.9.1 以降では、 Intel Xeon Sandy Bridge 以降に基づく CPU モデルのみがサポートされます。

を参照してください https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool 、ウィンドウ = _blank"] を参照してください。



=== 基本的なハードウェア要件

ノードに関係なく、すべてのプラットフォームに適用される一般的なハードウェア要件がいくつかあります。
インスタンスタイプまたはライセンス提案。

.プロセッサ
サポートされている\'83\'7dイクロプロセッサは、次のとおりです。

* サーバー向けインテル Xeon プロセッサー（を参照 link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["インテル Xeon プロセッサー、ウィンドウ = _ ブランク"] 詳細については、


.イーサネット構成
クラスタのサイズに基づいて、サポートされるイーサネット構成がいくつかあります。

[cols="30,35,35"]
|===


| クラスタサイズ | 最小要件 | スイシヨウヨウケン 


| シングルノードクラスタ | 1GbE×2 | 10GbE×2 


| 2ノードクラスタまたはMetroCluster SDS | 1GbE×4または10GbE×1 | 10GbE×2 


| 4 / 6 / 8ノードクラスタ | 10GbE×2 | 10GbE×4、または25/40GbE×2 
|===


=== インスタンスタイプに基づいた追加のハードウェア要件

ノードインスタンスのタイプに基づいて、ハードウェアに関する追加の要件がいくつかあります。

を参照してください link:concept_lic_platforms.html["プラットフォームのライセンス製品を理解する"] を参照してください。

.小規模
* CPUコア数
6個以上の物理コア（4個はONTAP Select用に予約）
* メモリ
24GB以上（16GBはONTAP Select用に予約）
* 必要なプラットフォームライセンスサービス
Standard、Premium、またはPremium XL


.中
* CPUコア数
10個以上の物理コア（8個はONTAP Select用に予約）
* メモリ
72GB以上（64GBはONTAP Select用に予約）
* 必要なプラットフォームライセンスサービス
プレミアムまたはプレミアムXL


.大規模
* CPUコア数
18個以上の物理コア、16個はONTAP Select用に予約されています。
* メモリ
136GB以上（128GBはONTAP Select用に予約）
* 必要なプラットフォームライセンスサービス
Premium XL



NOTE: プラットフォームライセンスに基づいて追加のディスクが必要になります。を参照してください link:reference_plan_ots_storage.html["ストレージと RAID"] を参照してください。
